// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZJaRtb0oYTuzUuXyagEfEUrCv-9s6UWw',
    appId: '1:489716296559:web:cfe649fb4552a8093dd69a',
    messagingSenderId: '489716296559',
    projectId: 'tasky-3c2f9',
    authDomain: 'tasky-3c2f9.firebaseapp.com',
    storageBucket: 'tasky-3c2f9.firebasestorage.app',
    measurementId: 'G-XM0Y69JPQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Y74Z1EiiWA1_7IZIuQuez12XOy8rX9c',
    appId: '1:489716296559:android:5ba3705e01e5fa0e3dd69a',
    messagingSenderId: '489716296559',
    projectId: 'tasky-3c2f9',
    storageBucket: 'tasky-3c2f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV2ZITR9OeuFS3mtAlQELFAsw1R4swj0M',
    appId: '1:489716296559:ios:0c41016ec95d75a73dd69a',
    messagingSenderId: '489716296559',
    projectId: 'tasky-3c2f9',
    storageBucket: 'tasky-3c2f9.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV2ZITR9OeuFS3mtAlQELFAsw1R4swj0M',
    appId: '1:489716296559:ios:0c41016ec95d75a73dd69a',
    messagingSenderId: '489716296559',
    projectId: 'tasky-3c2f9',
    storageBucket: 'tasky-3c2f9.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZJaRtb0oYTuzUuXyagEfEUrCv-9s6UWw',
    appId: '1:489716296559:web:4dae7a8fc9d1ab573dd69a',
    messagingSenderId: '489716296559',
    projectId: 'tasky-3c2f9',
    authDomain: 'tasky-3c2f9.firebaseapp.com',
    storageBucket: 'tasky-3c2f9.firebasestorage.app',
    measurementId: 'G-RS5LMNVSMP',
  );
}
